=== psmitt/psmitt.github.io/PowerShell/Menu.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT menu  (menu*)>
<!ATTLIST menu
          title  CDATA           #REQUIRED
          link   CDATA           #REQUIRED
          frame (Article|_blank) #IMPLIED>

=== psmitt/psmitt.github.io/PowerShell/hu-HU/Menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE syntax SYSTEM "../Menu.dtd">
<?xml-stylesheet type="text/xsl" href="../Menu.xsl"?>
<menu>
  <menu title="Első lépések, felderítőeszközök">
    <menu title="PowerShell parancsértelmező">
      <menu title="Áttekintés"      link="About_PowerShell"/>
      <menu title="Telepítés"       link="Install-PowerShell"/>
      <menu title="Verziófrissítés" link="Update-PowerShell"/>
      <menu title="Eltávolítás"     link="Remove-PowerShell"/>
    </menu>
    <menu title="Help tájékoztatórendszer">
      <menu title="Áttekintés" link="About_Help"/>
      <menu title="A súgó naprakészen tartása, frissítése" link="Update-Help"/>
      <menu title="A súgó használata" link="Get-Help"/>
    </menu>
    <menu title="Host - a parancssori ablak">
    </menu>
    <menu title="PSReadLine parancssorkezelő">
    </menu>
  </menu>
  <menu title="Adattárak, Tárkezelők, Alapparancsok, AdatTárHelyKezelők">
  </menu>
</menu>
